
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/admin_test
    driver-class-name: ${POSTGRESQL_JDBC_DRIVER:org.postgresql.Driver}
    username: admin
    password: admin
    hikari:
      maximum-pool-size: 10

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
      jdbc:
        lob:
          non_contextual_creation: true
      dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

  flyway:
    baseline-on-migrate: true
    locations: classpath:db.migration

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  address: ${HTTP_SERVER_HOST:0.0.0.0}
  port: ${HTTP_SERVER_PORT:8082}

logging:
  level:
    org:
      springframework:
        security: DEBUG