spring:
  datasource:
    url: ${POSTGRESQL_JDBC_URL:jdbc:postgresql://localhost:5432/test_task}
    driver-class-name: ${POSTGRESQL_JDBC_DRIVER:org.postgresql.Driver}
    username: ${POSTGRESQL_JDBC_USERNAME:admin}
    password: ${POSTGRESQL_JDBC_PASSWORD:admin}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
      jdbc:
        lob:
          non_contextual_creation: true
      dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  address: ${HTTP_SERVER_HOST:0.0.0.0}
  port: ${HTTP_SERVER_PORT:8082}

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG